/** Тексты отчёта. Отчёт собирается в ядре (детерминированно), поэтому и строки — здесь */
export const REPORT_LOCALES = ['ru', 'en'] as const
export type ReportLocale = (typeof REPORT_LOCALES)[number]

export const REPORT_STRINGS = {
  ru: {
    title: 'Мой impact log',
    period: 'Период',
    summary: 'Итоги',
    total: 'Записей',
    average: 'Средняя оценка влияния',
    high: 'Высокое влияние (4–5)',
    withMetrics: 'С измеримым результатом',
    withEvidence: 'С артефактами',
    categories: 'По категориям',
    topLabels: 'Частые метки',
    highlights: 'Ключевые результаты',
    all: 'Все записи',
    uncategorized: 'Без категории',
    score: 'Влияние',
    metrics: 'Результат',
    evidence: 'Артефакты',
    generated: 'Сформировано в impact log',
    noEntries: 'За этот период записей нет.',
    months: [
      'январь',
      'февраль',
      'март',
      'апрель',
      'май',
      'июнь',
      'июль',
      'август',
      'сентябрь',
      'октябрь',
      'ноябрь',
      'декабрь',
    ],
  },
  en: {
    title: 'My impact log',
    period: 'Period',
    summary: 'Summary',
    total: 'Entries',
    average: 'Average impact score',
    high: 'High impact (4–5)',
    withMetrics: 'With measurable outcome',
    withEvidence: 'With artifacts',
    categories: 'By category',
    topLabels: 'Frequent labels',
    highlights: 'Key results',
    all: 'All entries',
    uncategorized: 'Uncategorized',
    score: 'Impact',
    metrics: 'Outcome',
    evidence: 'Artifacts',
    generated: 'Generated with impact log',
    noEntries: 'No entries for this period.',
    months: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
  },
} as const satisfies Record<ReportLocale, unknown>
